language: cpp

compiler:
  - clang
  - gcc

before_install:
  # gcc-4.9
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # clang 3.4
  - if [ "$CC" == "clang" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake g++-4.9
  - sudo apt-get install -qq libmsgpack-dev libudt-dev 

  - if [ "$CC" = "gcc" ]; then
      export CC="gcc-4.9" &&
      export CXX="g++-4.9";
    fi

  - if [ "$CC" == "clang" ]; then
      sudo apt-get install --allow-unauthenticated -qq clang-3.4 &&
      export CC="clang-3.4" &&
      export CXX="clang++-3.4";
    fi

script:
   - cmake .
   - make
   - ctest --output-on-failure
